### ISSUE TITLE
How to use with xp-pages/mat-pages

### ISSUE THREAD

**Issue by mwinters-stuff** [expandjs/xp-router#1]
The "documentation" says it can be used with xp-pages, but no example is provided or details on how to implement this.
I was/am trying ti use the xp-router instead of more-router which works nicely, My webapp has a number of pages which show based on the route.. I cant seem to get this working with xp-route/xp-router

An example would be nice...

**Comment by Pupix** [comment]
The routing example is on the homepage at the bottom. We will move it into the documentation page very shortly.

Cheers!
